version: '3'

services:
  eventsourcing.in.api:
    image: ei8io/eventsourcing.in.api:0.1.5
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  eventsourcing.out.api:
    image: ei8io/eventsourcing.out.api:0.1.5
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  cortex.graph.persistence:
    image: arangodb:3.11.3
    ports:
#     - "XXXX:8529" - XXXX each instance of arangodb should bind to a distinct port in the neurUL server
      - "8529:8529"
    volumes:
      - ./arangodb/:/var/lib/arangodb3
    env_file:
      - ./variables.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8529 || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
  cortex.graph.in.api:
    image: ei8io/cortex.graph.in.api:0.3.9
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    depends_on:
      "cortex.graph.persistence":
        condition: service_healthy
  cortex.graph.out.api:
    image: ei8io/cortex.graph.out.api:0.3.9
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    depends_on:
      "cortex.graph.persistence":
        condition: service_healthy
  cortex.diary.nucleus.in.api:
    image: ei8io/cortex.diary.nucleus.in.api:0.2.7
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
      - SUBSCRIPTIONS_IN_BASE_URL=http://cortex.subscriptions.in.api:80
      - SUBSCRIPTIONS_OUT_BASE_URL=http://cortex.subscriptions.out.api:80
  cortex.diary.nucleus.out.api:
    image: ei8io/cortex.diary.nucleus.out.api:0.2.7
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
      - SUBSCRIPTIONS_IN_BASE_URL=http://cortex.subscriptions.in.api:80
      - SUBSCRIPTIONS_OUT_BASE_URL=http://cortex.subscriptions.out.api:80
  cortex.library.out.api:
    image: ei8io/cortex.library.out.api:0.2.6
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
  avatar.in.api:
    image: ei8io/avatar.in.api:0.2.0
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
    ports:
      - ${AVATAR_IP}:${AVATAR_IN_PORT}:80
  cortex.identityaccess.in.api:
    image: ei8io/cortex.identityaccess.in.api:0.2.5
    env_file: 
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    volumes:
      - ./:/C/db
  cortex.identityaccess.out.api:
    image: ei8io/cortex.identityaccess.out.api:0.2.5
    env_file: 
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    volumes:
      - ./:/C/db
  cortex.subscriptions.in.api:
    image: ei8works/cortex.subscriptions.in.api:0.1.2
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  cortex.subscriptions.out.api:
    image: ei8works/cortex.subscriptions.out.api:0.1.2
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  un8y.api:
    image: ei8io/un8y.api:0.4.0
    env_file:
      - ./un8y/variables.env
    expose:
      - "80"
      - "${UN8Y_BLAZOR_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:${UN8Y_BLAZOR_PORT};http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./:/C/db
    ports:
      - ${UN8Y_IP}:${UN8Y_BLAZOR_PORT}:${UN8Y_BLAZOR_PORT}
  cortex.chat.nucleus.in.api:
    image: ei8io/cortex.chat.nucleus.in.api:0.3.0
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_LIBRARY_OUT_BASE_URL=http://cortex.library.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
    volumes:
      - ./chat-nucleus-settings.json:/app/appsettings.json
  cortex.chat.nucleus.out.api:
    image: ei8io/cortex.chat.nucleus.out.api:0.3.0
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_LIBRARY_OUT_BASE_URL=http://cortex.library.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
    volumes:
      - ./chat-nucleus-settings.json:/app/appsettings.json
