version: '3'

services:
  eventsourcing.in.api:
    image: ei8works/eventsourcing.in.api:0.1.3
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  eventsourcing.out.api:
    image: ei8works/eventsourcing.out.api:0.1.3
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  cortex.graph.persistence:
    image: arangodb:3.11.3
    ports:
      - "8529:8529"
    volumes:
      - ./arangodb/:/var/lib/arangodb3
    env_file:
      - ./variables.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8529 || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
  cortex.graph.in.api:
    image: ei8io/cortex.graph.in.api:0.3.3
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    depends_on:
      "cortex.graph.persistence":
        condition: service_healthy
  cortex.graph.out.api:
    image: ei8io/cortex.graph.out.api:0.3.3
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    depends_on:
      "cortex.graph.persistence":
        condition: service_healthy
  cortex.diary.nucleus.in.api:
    image: ei8works/cortex.diary.nucleus.in.api:0.2.5
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
      - SUBSCRIPTIONS_IN_BASE_URL=http://cortex.subscriptions.in.api:80
      - SUBSCRIPTIONS_OUT_BASE_URL=http://cortex.subscriptions.out.api:80
  cortex.diary.nucleus.out.api:
    image: ei8works/cortex.diary.nucleus.out.api:0.2.5
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
      - SUBSCRIPTIONS_IN_BASE_URL=http://cortex.subscriptions.in.api:80
      - SUBSCRIPTIONS_OUT_BASE_URL=http://cortex.subscriptions.out.api:80
  cortex.library.out.api:
    image: ei8works/cortex.library.out.api:0.2.0
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
  avatar.in.api:
    image: ei8works/avatar.in.api:0.1.14
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
    ports:
      - ${AVATAR_IP}:${AVATAR_IN_PORT}:80
  cortex.identityaccess.in.api:
    image: ei8works/cortex.identityaccess.in.api:0.2.3
    env_file: 
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    volumes:
      - ./:/C/db
  cortex.identityaccess.out.api:
    image: ei8works/cortex.identityaccess.out.api:0.2.3
    env_file: 
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_GRAPH_OUT_BASE_URL=http://cortex.graph.out.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
    volumes:
      - ./:/C/db
  cortex.subscriptions.in.api:
    image: ei8works/cortex.subscriptions.in.api:0.1.2
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  cortex.subscriptions.out.api:
    image: ei8works/cortex.subscriptions.out.api:0.1.2
    env_file:
      - ./variables.env
    expose:
      - "80"
    volumes:
      - ./:/C/db
  d23.api:
    image: ei8io/d23.api:0.3.9
    env_file:
      - ./d23-variables.env
    expose:
      - "80"
      - "${D23_BLAZOR_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${D23_BLAZOR_PORT};http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./:/C/db
    ports:
      - ${D23_IP}:${D23_BLAZOR_PORT}:${D23_BLAZOR_PORT}
  cortex.chat.nucleus.in.api:
    image: ei8io/cortex.chat.nucleus.in.api:0.1.4
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_LIBRARY_OUT_BASE_URL=http://cortex.library.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80
  cortex.chat.nucleus.out.api:
    image: ei8io/cortex.chat.nucleus.out.api:0.1.4
    env_file:
      - ./variables.env
    expose:
      - "80"
    environment:
      - CORTEX_LIBRARY_OUT_BASE_URL=http://cortex.library.out.api:80
      - EVENT_SOURCING_IN_BASE_URL=http://eventsourcing.in.api:80
      - EVENT_SOURCING_OUT_BASE_URL=http://eventsourcing.out.api:80
      - IDENTITY_ACCESS_IN_BASE_URL=http://cortex.identityaccess.in.api:80
      - IDENTITY_ACCESS_OUT_BASE_URL=http://cortex.identityaccess.out.api:80